version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=YourStrong@Passw0rd
      - POSTGRES_DB=CleanArchitectureDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=CleanArchitectureDb;Username=sa;Password=YourStrong@Passw0rd
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data: 